Repository thoth-station/common, pull requests merged in 2018-08, with the labels that each got.

#51 Automatic update of dependency pylint from 2.0.1 to 2.1.0
  Pipfile.lock
Labels: bot

#53 Automatic update of dependency pytest from 3.7.0 to 3.7.1
  Pipfile.lock
Labels: bot

#61 Automatic update of dependency pytest-timeout from 1.3.1 to 1.3.2
  Pipfile.lock
Labels: bot

#65 Release of version 0.2.3
  thoth/common/__init__.py
Labels: bot, size/XS

#66 Pin down Kubernetes and OpenShift clients to specific versions
  setup.py
Labels: approved, size/XS

#69 Release of version 0.2.4
  thoth/common/__init__.py
Labels: bot, size/XS

#71 Configure SSL/TLS correctly when communicating with master
  thoth/common/openshift.py
Labels: size/XS

#73 Release of version 0.2.5
  thoth/common/__init__.py
Labels: bot, size/XS
