Repository thoth-station/common, pull requests merged in 2018-11, with the labels that each got.

#195 Automatic update of dependency pytest from 3.9.3 to 3.10.0
  Pipfile.lock
Labels: bot

#194 Introduce method for creating datetime from timestamp
  thoth/common/__init__.py
  thoth/common/helpers.py
Labels: approved, size/XS

#197 Release of version 0.4.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#198 Automatic update of dependency sentry-sdk from 0.5.2 to 0.5.3
  Pipfile.lock
Labels: bot

#200 Automatic update of dependency requests from 2.20.0 to 2.20.1
  Pipfile.lock
Labels: bot

#201 Automatic update of dependency sentry-sdk from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#202 Automatic update of dependency pytest from 3.10.0 to 3.10.1
  Pipfile.lock
Labels: bot

#206 Automatic update of dependency pytest from 3.10.1 to 4.0.0
  Pipfile.lock
Labels: bot

#209 Automatic update of dependency sentry-sdk from 0.5.4 to 0.5.5
  Pipfile.lock
Labels: bot

#210 Propagate dependency monkey parameters to template
  thoth/common/openshift.py
Labels: size/S

#213 Add count parameter to dependency monkey
  thoth/common/openshift.py
Labels: approved, size/S

#205 Use api version from template
  thoth/common/openshift.py
Labels: approved, size/S

#216 Release of version 0.4.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#215 Automatic update of dependency pytest-timeout from 1.3.2 to 1.3.3
  Pipfile.lock
Labels: bot

#217 Introduce method for getting build in a namespace
  thoth/common/openshift.py
Labels: size/S

#221 Introduce count and limit for adviser
  thoth/common/openshift.py
Labels: size/S, size/XS

#223 Release of version 0.4.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#224 Introduce method for gathering buildconfigs
  thoth/common/openshift.py
Labels: approved, size/S

#227 Release of version 0.4.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#228 Runtime environment is now a dict
  thoth/common/openshift.py
Labels: size/XS

#231 Adjust force sync to respect implementation
  thoth/common/openshift.py
Labels: size/XS

#232 Supply whitelisted sources to provenance checks
  thoth/common/openshift.py
Labels: size/XS

#234 Automatic update of dependency pytest from 4.0.0 to 4.0.1
  Pipfile.lock
Labels: bot

#236 Propagate index urls into solver runs
  thoth/common/openshift.py
Labels: approved, size/XS

#237 Automatic update of dependency pylint from 2.2.0 to 2.2.1
  Pipfile.lock
Labels: bot

#233 Add long description for PyPI
  setup.py
Labels: approved, size/XS

#230 Release of version 0.4.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#238 Automatic update of dependency pylint from 2.2.1 to 2.2.2
  Pipfile.lock
Labels: bot
