Repository thoth-station/common, pull requests merged in 2018-12, with the labels that each got.

#240 Release of version 0.4.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#241 Automatic update of dependency sentry-sdk from 0.5.5 to 0.6.0
  Pipfile.lock
Labels: bot

#244 Propagate count to dependency monkey runs
  thoth/common/openshift.py
Labels: size/XS

#242 Solver now accepts subgraph check API parameter
  thoth/common/openshift.py
Labels: size/S, size/XS

#245 Fix env variable typo
  thoth/common/openshift.py
Labels: size/XS

#246 Dependency monkey can accept a serialized JSON representing Pipfile
  thoth/common/openshift.py
Labels: size/XS

#247 Automatic update of dependency sentry-sdk from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#250 Release of version 0.5.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#252 Automatic update of dependency pytest from 4.0.1 to 4.0.2
  Pipfile.lock
Labels: bot

#253 Automatic update of dependency sentry-sdk from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#255 Automatic update of dependency sentry-sdk from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot
