Repository thoth-station/common, pull requests merged in 2018-10, with the labels that each got.

#128 Automatic update of dependency sentry-sdk from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#129 Automatic update of dependency sentry-sdk from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#130 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#131 Automatic update of dependency sentry-sdk from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#132 Introduce methods for running dependency monkey
  thoth/common/openshift.py
Labels: approved, size/L

#133 Make reusable methods public
  thoth/common/openshift.py
Labels: size/M

#138 Add routines for jobs handling
  thoth/common/openshift.py
Labels: size/S

#136 Gather build logs from OpenShift
  thoth/common/openshift.py
Labels: size/S

#135 Allow explicitly specifying the logging configuration prefix
  thoth/common/logging.py
Labels: size/S

#139 Automatic update of dependency sentry-sdk from 0.3.9 to 0.3.11
  Pipfile.lock
Labels: bot

#141 Release of version 0.3.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#143 Fix undefined name error
  thoth/common/openshift.py
Labels: size/XS

#144 Automatic update of dependency sentry-sdk from 0.3.11 to 0.4.0
  Pipfile.lock
Labels: bot

#147 Release of version 0.3.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#145 Fix gathering pod id from job name
  thoth/common/openshift.py
Labels: approved, size/XS

#149 Release of version 0.3.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#142 Raise appropriate not found exception exception
  thoth/common/openshift.py
Labels: size/S

#153 Release of version 0.3.10
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#155 Fix syntax error
  thoth/common/openshift.py
Labels: approved, size/XS

#158 Automatic update of dependency sentry-sdk from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#161 Default to now if no datetime was provided
  thoth/common/helpers.py
Labels: size/XS

#162 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#163 Automatic update of dependency sentry-sdk from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#166 Automatic update of dependency sentry-sdk from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#167 added get_jobs(), it will be used for thoth-metrics
  thoth/common/openshift.py
Labels: approved, size/S

#168 Automatic update of dependency rfc5424-logging-handler from 1.2.1 to 1.3.0
  Pipfile.lock
Labels: bot

#170 Release of version 0.3.12
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#171 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#172 Automatic update of dependency sentry-sdk from 0.4.3 to 0.5.0
  Pipfile.lock
Labels: bot

#174 Add InClusterConfigLoader to load SA and cert
  thoth/common/helpers.py
  thoth/common/openshift.py
Labels: approved, size/L, size/S

#176 Automatic update of dependency pytest from 3.9.2 to 3.9.3
  Pipfile.lock
Labels: bot

#175 Refactor methods into pythonic way
  thoth/common/helpers.py
  thoth/common/openshift.py
Labels: approved, size/S

#182 Release of version 0.3.14
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#184 Do not propagate force to actual package-extract run
  thoth/common/openshift.py
Labels: approved, size/XS

#186 Report error if sentry initialization fails
  thoth/common/logging.py
Labels: approved, size/S

#187 Make all datetimes timezone aware
  thoth/common/helpers.py
Labels: approved, size/S

#189 Release of version 0.3.15
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#190 Make CI happy again
  thoth/common/helpers.py
  thoth/common/logging.py
Labels: approved, size/XS

#191 Fix missing import
  thoth/common/helpers.py
Labels: size/XS

#193 Release of version 0.3.16
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#185 using thoht-* jobs now
  .coafile
  .zuul.yaml
Labels: approved, size/M
