Repository thoth-station/common, pull requests merged in 2018-09, with the labels that each got.

#75 Fix TLS/SSL certification verification configuration
  thoth/common/openshift.py
Labels: approved, size/XS

#78 Release of version 0.2.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#77 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#80 Fix default TLS verification behavior
  thoth/common/openshift.py
Labels: approved, size/XS

#82 Release of version 0.2.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#79 Introduce routine for running provenance checker
  thoth/common/openshift.py
Labels: approved, size/M

#86 Fix propagating debug flag to package-extract
  thoth/common/openshift.py
Labels: approved, size/XS

#84 Fix gathering pod status for default middletier namespace
  thoth/common/openshift.py
Labels: approved, size/XS

#87 Issue warning on suspicious parameter expansion in templates
  thoth/common/openshift.py
Labels: approved, size/XS

#85 Fix gathering pod logs for default middletier namespace
  thoth/common/openshift.py
Labels: approved, size/XS

#88 Let's reuse adviser env var names
  thoth/common/openshift.py
Labels: size/XS

#90 Release of version 0.3.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#93 Automatic update of dependency pytest from 3.7.4 to 3.8.0
  Pipfile.lock
Labels: bot

#91 Fix built-in type shadowing
  thoth/common/openshift.py
Labels: approved, size/XS

#100 Release of version 0.3.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#104 Unify pod status reports
  thoth/common/openshift.py
Labels: approved, size/M

#103 Treat None parameter values as empty values
  thoth/common/openshift.py
Labels: approved, size/XS

#105 Automatic update of dependency rfc5424-logging-handler from 1.1.2 to 1.2.1
  Pipfile.lock
Labels: bot

#106 Automatic update of dependency pytest from 3.8.0 to 3.8.1
  Pipfile.lock
Labels: bot

#102 Report back empty pod status is pod is being scheduled
  thoth/common/openshift.py
Labels: size/S, size/XS

#107 Report scheduling status if pod was not initialized yet
  thoth/common/openshift.py
Labels: size/XS

#108 Add Sentry support
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/common/logging.py
Labels: size/L

#111 Release of version 0.3.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#110 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#112 Automatic update of dependency sentry-sdk from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot

#115 fixed the typo
  thoth/common/logging.py
Labels: size/S

#117 Release of version 0.3.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#120 Release of version 0.3.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/L

#123 Release of version 0.3.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/L

#125 fixed a few typos
  thoth/common/openshift.py
Labels: size/L

#127 Release of version 0.3.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS
