Repository thoth-station/common, pull requests merged in 2018-07, with the labels that each got.

#32 Introduce a function for getting service account token
  thoth/common/__init__.py
  thoth/common/helpers.py
Labels: approved, size/S

#37 catching and logging a "[Errno -2] Name or service not known"
  thoth/common/logging.py
Labels: approved

#40 Fix syntax error in logging
  thoth/common/logging.py
Labels: approved

#39 Initial dependency lock
  Pipfile.lock
Labels: bot

#43 Automatic update of dependency daiquiri from 1.3.0 to 1.5.0
  Pipfile.lock
Labels: approved, bot

#45 Automatic update of dependency pytest-timeout from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: approved, bot

#44 Automatic update of dependency pylint from 1.9.2 to 2.0.1
  Pipfile.lock
Labels: approved, bot

#46 Allow completely suppressing logs
  thoth/common/logging.py
Labels: approved, size/S

#49 Release of version 0.2.2
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#47 Automatic update of dependency pytest from 3.6.3 to 3.6.4
  Pipfile.lock
Labels: bot

#50 Automatic update of dependency pytest from 3.6.4 to 3.7.0
  Pipfile.lock
Labels: bot
