Repository thoth-station/common, pull requests merged in 2018-06, with the labels that each got.

#24 Setup logging for root logger
  thoth/common/logging.py
Labels: approved, size/S

#23 Disable annoying unverified HTTPS warnings
  thoth/common/logging.py
Labels: approved, size/S

#26 Added daiquiri
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/common/logging.py
Labels: approved, size/M

#27 Fix logging issues
  thoth/common/logging.py
Labels: approved, size/XS

#28 Generic wrappers to define verbose level on every method
  thoth/common/__init__.py
  thoth/common/logging.py
Labels: approved, size/S

#29 preparing release 0.0.8: Zuul
  .coafile
  .zuul.yaml
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  thoth/common/__init__.py
  thoth/common/logging.py
Labels: approved, size/L

#30 added the gate pipeline to the core queue
  .zuul.yaml
Labels: approved, size/XS

#31 Change in var name
  thoth/common/logging.py
Labels: approved, size/XS
