Repository thoth-station/common, pull requests merged in 2019-08, with the labels that each got.

#450 New function to count status of specific jobs identifed by label, in a certain namespace
  thoth/common/openshift.py
Labels: approved, size/M

#451 Automatic update of dependency daiquiri from 1.5.0 to 1.6.0
  Pipfile.lock
Labels: bot

#452 Kebechet
  thoth/common/openshift.py
Labels: approved, size/S

#454 Release of version 0.9.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#455 Leftover parameter from copy paste
  thoth/common/openshift.py
Labels: approved, size/XS

#456 As we use Thoth to resolve dependencies, stop using extras
  requirements.txt
  setup.py
Labels: size/XS

#458 Release of version 0.9.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#459 Do not pin to a specific Kubernetes release
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/M

#461 Release of version 0.9.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#462 Be consistent with solver type labels
  thoth/common/openshift.py
Labels: approved, size/XS

#463 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#464 Automatic update of dependency sentry-sdk from 0.10.2 to 0.11.0
  Pipfile.lock
Labels: bot

#465 Automatic update of dependency sentry-sdk from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#466 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#469 Automatic update of dependency sentry-sdk from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#470 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
