Repository thoth-station/common, pull requests merged in 2019-03, with the labels that each got.

#323 Automatic update of dependency rfc5424-logging-handler from 1.4.0 to 1.4.1
  Pipfile.lock
Labels: bot

#328 Automatic update of dependency sentry-sdk from 0.7.2 to 0.7.4
  Pipfile.lock
Labels: bot

#325 Automatic update of dependency openshift from 0.8.5 to 0.8.6
  Pipfile.lock
Labels: bot

#326 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot

#329 Automatic update of dependency pylint from 2.2.2 to 2.3.0
  Pipfile.lock
Labels: bot

#333 Introduce limit latest versions parameter
  thoth/common/openshift.py
Labels: size/S

#332 Do not consider nested none values in output if with_none is false
  thoth/common/config/runtime_environment.py
Labels: size/S

#334 Automatic update of dependency sentry-sdk from 0.7.4 to 0.7.6
  Pipfile.lock
Labels: bot

#338 Release of version 0.8.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#335 Automatic update of dependency attrs from 18.2.0 to 19.1.0
  Pipfile.lock
Labels: bot

#336 Automatic update of dependency pytest from 4.3.0 to 4.3.1
  Pipfile.lock
Labels: bot

#337 Automatic update of dependency pylint from 2.3.0 to 2.3.1
  Pipfile.lock
Labels: bot

#339 Automatic update of dependency pyyaml from 3.13 to 5.1
  Pipfile.lock
Labels: bot

#340 Use Sphinx for documentation
  .coafile
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
  thoth/common/logging.py
  thoth/common/openshift.py
Labels: size/L

#341 Lock Kubernetes and OpenShift to specific version
  Pipfile
  Pipfile.lock
  setup.py
Labels: size/S

#344 Lock Kubernetes and OpenShift to specific version
  Pipfile
  Pipfile.lock
  setup.py
Labels: size/S

#345 Release of version 0.8.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#346 Propagate metadata about runtime and buildtime environment
  thoth/common/openshift.py
Labels: size/S

#347 Fix serialization of runtime environment
  thoth/common/config/runtime_environment.py
Labels: size/S

#349 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#350 Automatic update of dependency sentry-sdk from 0.7.6 to 0.7.7
  Pipfile.lock
Labels: bot

#351 Automatic update of dependency sentry-sdk from 0.7.7 to 0.7.8
  Pipfile.lock
Labels: bot

#352 Automatic update of dependency sentry-sdk from 0.7.8 to 0.7.9
  Pipfile.lock
Labels: bot

#353 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
