Repository thoth-station/common, pull requests merged in 2019-09, with the labels that each got.

#472 Add dry-run to package-analyzer
  thoth/common/openshift.py
Labels: approved, size/XS

#473 Schedule solvers without transitive flag being set by default
  thoth/common/openshift.py
Labels: approved, size/XS

#474 Automatic update of dependency sentry-sdk from 0.11.2 to 0.12.0
  Pipfile.lock
Labels: bot

#476 Release of version 0.9.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#477 Hotfix for errors when getting solver templates
  thoth/common/openshift.py
Labels: size/XS

#479 Release of version 0.9.10
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#480 Automatic update of dependency sentry-sdk from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot

#481 Automatic update of dependency sentry-sdk from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot

#482 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#483 Automatic update of dependency pylint from 2.3.1 to 2.4.0
  Pipfile.lock
Labels: bot

#485 Improve error message shown when getting cluster resources
  thoth/common/openshift.py
Labels: approved, size/XS

#486 Automatic update of dependency pylint from 2.4.0 to 2.4.1
  Pipfile.lock
Labels: bot

#488 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#489 Automatic update of dependency pylint from 2.4.1 to 2.4.2
  Pipfile.lock
Labels: bot
