Repository thoth-station/common, pull requests merged in 2019-05, with the labels that each got.

#376 Automatic update of dependency pytest-cov from 2.6.1 to 2.7.0
  Pipfile.lock
Labels: bot

#377 Automatic update of dependency pytest-cov from 2.7.0 to 2.7.1
  Pipfile.lock
Labels: bot

#378 Minor fix to display correct release in title of docs html
  setup.py
Labels: approved, size/XS

#379 Propagate library usage to adviser runs
  thoth/common/openshift.py
Labels: approved, size/XS

#380 Ensure recommendation type is in upper case
  thoth/common/openshift.py
Labels: size/XS

#382 Release of version 0.8.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#384 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#385 Provide default for limit latest versions
  thoth/common/openshift.py
Labels: size/XS

#386 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#389 Release of version 0.8.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot

#390 Release of version 0.8.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot

#391 Release of version 0.8.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot

#392 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#393 Automatic update of dependency sentry-sdk from 0.7.14 to 0.8.0
  Pipfile.lock
Labels: bot

#394 Automatic update of dependency rfc5424-logging-handler from 1.4.2 to 1.4.3
  Pipfile.lock
Labels: approved, bot

#395 minor fix for correct namespace
  thoth/common/openshift.py
Labels: approved

#396 minor fix of error msg
  thoth/common/openshift.py
Labels: approved, size/XS
