Repository thoth-station/common, pull requests merged in 2019-04, with the labels that each got.

#355 Release of version 0.8.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#357 refactored retrieval of template
  thoth/common/logging.py
  thoth/common/openshift.py
Labels: size/L

#361 Release of version 0.8.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#362 Automatic update of dependency sentry-sdk from 0.7.9 to 0.7.10
  Pipfile.lock
Labels: bot

#363 Obtain templates from Amun infra for Amun specific templates
  thoth/common/openshift.py
Labels: approved, size/S

#365 Release of version 0.8.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#366 :pushpin: Automatic update of dependency rfc5424-logging-handler from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: bot, size/S

#367 Fix inspection and inspect bad interpretation
  thoth/common/openshift.py
Labels: approved, size/S

#369 Release of version 0.8.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#370 Add missing requests library to requirements
  requirements.txt
Labels: approved, size/XS

#371 Automatic update of dependency pytest from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#373 Automatic update of dependency sentry-sdk from 0.7.11 to 0.7.12
  Pipfile.lock
Labels: bot

#374 Automatic update of dependency sentry-sdk from 0.7.12 to 0.7.13
  Pipfile.lock
Labels: bot

#375 Automatic update of dependency sentry-sdk from 0.7.13 to 0.7.14
  Pipfile.lock
Labels: bot
