Repository thoth-station/common, pull requests merged in 2019-02, with the labels that each got.

#275 Fix coala errors
  thoth/common/logging.py
  thoth/common/openshift.py
Labels: human_intervention_required, size/S, size/XS

#300 Automatic update of dependency sentry-sdk from 0.6.9 to 0.7.2
  Pipfile.lock
Labels: bot

#296 Automatic update of dependency pytest from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#295 Automatic update of dependency rfc5424-logging-handler from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: bot

#301 Introduce runtime environment abstractions
  .gitignore
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/common/__init__.py
  thoth/common/config/__init__.py
  thoth/common/config/base.py
  thoth/common/config/hardware_information.py
  thoth/common/config/operating_system.py
  thoth/common/config/runtime_environment.py
  thoth/common/openshift.py
Labels: size/L

#302 Also install the missing config module
  setup.py
Labels: size/XS

#303 Load runtime environment transparently from YAML/JSON file
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/common/config/runtime_environment.py
Labels: size/S

#305 Optionally provide dict representation without none values
  thoth/common/config/base.py
  thoth/common/config/runtime_environment.py
Labels: size/S

#306 Add check for runtime environment name
  thoth/common/config/runtime_environment.py
Labels: size/XS

#308 Runtime environment can be set to None
  thoth/common/config/runtime_environment.py
Labels: size/XS

#312 Propagate document ID into graph-sync job name
  thoth/common/openshift.py
Labels: size/XS

#311 Check for ConfigMap presence to report registered workload to user
  thoth/common/logging.py
  thoth/common/openshift.py
Labels: size/M

#314 Graph syncs are unique per document id, no need to have long ids
  setup.py
  thoth/common/openshift.py
Labels: size/XS

#315 Release of version 0.7.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#318 Release of version 0.7.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#316 Automatic update of dependency openshift from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#321 Add format_datetime method to convert datetimes to default format
  thoth/common/helpers.py
Labels: approved, size/S, size/XS

#322 Propagate origin as metadata
  thoth/common/openshift.py
Labels: size/S
