Repository thoth-station/common, pull requests merged in 2019-07, with the labels that each got.

#427 Introduce graph sync multiple
  thoth/common/openshift.py
Labels: approved, size/M

#428 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#429 Automatic update of dependency sentry-sdk from 0.9.5 to 0.10.0
  Pipfile.lock
Labels: bot

#431 Increase the limit for file line size
  .coafile
Labels: approved, size/XS

#433 Automatic update of dependency sentry-sdk from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot

#434 Fix wrong argument handling
  thoth/common/openshift.py
Labels: approved, size/S

#436 Release of version 0.9.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#430 Kebechet
  thoth/common/openshift.py
Labels: approved, size/L, size/M

#437 Increase maximum lines per file
  .coafile
Labels: size/XS

#432 Support for build analysers scheduling
  thoth/common/openshift.py
Labels: approved, size/L

#439 Release of version 0.9.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#441 Automatic update of dependency sentry-sdk from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot

#442 Changed env variable names
  thoth/common/openshift.py
Labels: approved, size/S

#443 schedule_package_analyzer
  thoth/common/openshift.py
Labels: approved, do-not-merge/work-in-progress, size/M

#445 Release of version 0.9.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#446 Modified the names to standard convention
  thoth/common/openshift.py
Labels: approved, size/L

#448 Release of version 0.9.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#449 Automatic update of dependency pyyaml from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
