Repository thoth-station/common, pull requests merged in 2019-10, with the labels that each got.

#490 Automatic update of dependency attrs from 19.1.0 to 19.2.0
  Pipfile.lock
Labels: bot

#493 Release of version 0.9.11
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#494 Automatic update of dependency sentry-sdk from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot

#497 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#498 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#499 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#495 Drop subgraph check
  thoth/common/openshift.py
Labels: approved, size/XS

#492 Refactor out scheduling graph syncs
  thoth/common/openshift.py
Labels: size/L

#502 Add warnings when there is something fishy in environment configuration for logging
  thoth/common/logging.py
Labels: approved, size/XS

#503 Release of version 0.9.12
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#505 Release of version 0.9.13
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#501 Always log in UTC to be consistent with team members all over the world
  thoth/common/logging.py
Labels: approved, size/S

#506 relocked dependencies, cleaned up the coala deps
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#507 Propagate is_external flag to package-extract runs
  thoth/common/openshift.py
Labels: approved, size/S

#509 Fix method name to comply with other methods
  thoth/common/openshift.py
Labels: approved, size/XS

#512 Release of version 0.9.14
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/L

#513 Automatic update of dependency attrs from 19.2.0 to 19.3.0
  Pipfile.lock
Labels: bot

#515 Automatic update of dependency sentry-sdk from 0.12.3 to 0.13.0
  Pipfile.lock
Labels: bot

#518 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#519 Automatic update of dependency sentry-sdk from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot

#520 Start using mypy for type checking
  .gitignore
  .zuul.yaml
  Pipfile
  Pipfile.lock
  mypy.ini
  setup.py
  thoth/common/__init__.py
  thoth/common/config/__init__.py
  thoth/common/config/base.py
  thoth/common/config/runtime_environment.py
  thoth/common/helpers.py
  thoth/common/json.py
  thoth/common/logging.py
  thoth/common/openshift.py
  thoth/common/py.typed
Labels: approved, size/XL
