Repository thoth-station/common, pull requests merged in 2019-01, with the labels that each got.

#256 Make limit and count optional parameters for adviser template
  thoth/common/openshift.py
Labels: size/S

#257 Report template parameters in debug mode
  thoth/common/openshift.py
Labels: size/XS

#259 Introduce schedule methods for workload operator
  thoth/common/openshift.py
Labels: size/L

#260 Remove self from propagated parameters to configmap
  thoth/common/openshift.py
Labels: size/XS

#263 Workload operator expects method, not method_name
  thoth/common/openshift.py
Labels: size/XS

#264 Move Amun specific pieces to OpenShift class
  thoth/common/openshift.py
Labels: size/L

#265 Enable local development for OpenShift client
  Pipfile
  Pipfile.lock
  thoth/common/openshift.py
Labels: size/L

#266 Add routines for workload operator
  thoth/common/openshift.py
Labels: size/XL

#268 Add routine for scheduling all registered solvers
  thoth/common/openshift.py
Labels: size/S

#269 Check running workload based on quota
  thoth/common/openshift.py
Labels: size/L

#270 Amun does not use Thoth's infra namespace
  thoth/common/openshift.py
Labels: size/S

#273 Fix incorrect use of infra namespace
  thoth/common/openshift.py
Labels: size/XS

#276 Fix how amun and thoth infra namespace is handled
  thoth/common/openshift.py
Labels: size/S

#277 Fix issues when template does not request any resources
  thoth/common/openshift.py
Labels: size/XS

#278 Assing memory and cpu requests when getting template
  thoth/common/openshift.py
Labels: size/M

#279 Explicitly assign inspection requests
  thoth/common/openshift.py
Labels: size/S

#281 Propagate graph-sync job id into template
  thoth/common/openshift.py
Labels: size/XS

#282 Treat builds as workload
  thoth/common/openshift.py
Labels: size/M

#283 Fix in template gathering for inspection build
  thoth/common/openshift.py
Labels: size/XS

#284 Label workload to allow type specific queries
  thoth/common/openshift.py
Labels: size/S

#285 Parse requests for build workload
  thoth/common/openshift.py
Labels: size/M

#291 A temporary workaround for workload management
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: size/S

#290 Disable urllib3 warnings
  thoth/common/openshift.py
Labels: size/XS

#287 Parse requests for build workload
  thoth/common/openshift.py
Labels: size/S

#292 Revert "A temporary workaround for workload management"
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: size/S

#293 Release of version 0.6.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/M

#297 Introduce method for scheduling adviser graph syncs
  thoth/common/openshift.py
Labels: size/XS
