Repository thoth-station/common, pull requests merged in 2019-11, with the labels that each got.

#521 Automatic update of dependency pytest-mypy from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#524 Fix boolean types in mypy.ini
  mypy.ini
Labels: approved, size/S

#525 Automatic update of dependency sentry-sdk from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot

#526 Provide a method to check if the given environment is fully specified
  thoth/common/config/runtime_environment.py
Labels: approved, size/S

#528 Release of version 0.9.15
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#530 Do not propagate private property on to_dict()
  thoth/common/config/runtime_environment.py
Labels: size/XS

#532 Release of version 0.9.16
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/L

#529 Enable running pytest for testsuite implementation
  setup.py
  tests/__init__.py
Labels: approved, size/S

#533 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/M

#523 Workflow management
  Pipfile
  Pipfile.lock
  fixtures/workflows/hello-world.yaml
  mypy.ini
  requirements.txt
  tests/workflows.py
  thoth/__init__.pyi
  thoth/common/__init__.py
  thoth/common/exceptions.py
  thoth/common/helpers.py
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: size/XL

#535 Fix error due to ambiguous template resources
  thoth/common/openshift.py
Labels: approved, size/XS

#537 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#538 Automatic update of dependency argo-workflows from 2.1.0 to 2.1.1
  Pipfile.lock
Labels: bot, size/S

#539 Enable Sentry integrations
  README.rst
  thoth/common/logging.py
Labels: approved, size/M

#540 Add few notes about logging to the README file
  README.rst
Labels: approved, size/S

#541 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#536 Inspection workflow
  thoth/common/workflows.py
Labels: approved, size/M

#543 Automatic update of dependency sentry-sdk from 0.13.2 to 0.13.3
  Pipfile.lock
Labels: bot, size/S

#544 Automatic update of dependency argo-workflows from 2.1.1 to 2.1.2
  Pipfile.lock
Labels: bot, size/S

#545 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/S

#546 Automatic update of dependency sentry-sdk from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/XS

#542 Add configuration of ignored loggers
  README.rst
  thoth/common/logging.py
Labels: size/S

#552 :pushpin: Relock
  Pipfile.lock
Labels: approved, size/S

#551 Make workflow management publicly consumable
  thoth/common/workflows.py
Labels: approved, size/L

#555 Release of version 0.9.17
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/M

#549 Propagate document id into templates
  thoth/common/openshift.py
Labels: approved, size/M

#557 Release of version 0.9.18
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#558 Library fixes
  mypy.ini
  tests/test_workflows.py
  thoth/__init__.pyi
  thoth/common/__init__.py
Labels: approved, size/S

#559 Release of version 0.9.19
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#560 Automatic update of dependency mypy from 0.740 to 0.750
  Pipfile.lock
Labels: bot, size/M
