Repository thoth-station/common, pull requests merged in 2019-12, with the labels that each got.

#562 Allow for different workflow and template namespaces
  thoth/common/workflows.py
Labels: approved, size/S

#563 Fixed accessor to amun_infra_namespace attribute
  thoth/common/workflows.py
Labels: approved, size/XS

#564 Fixed ResourceNotUniqueError in get_solver_names
  thoth/common/openshift.py
Labels: approved, size/XS

#565 Inspection Workflow template is stored in amun infra
  thoth/common/workflows.py
Labels: approved, size/XS

#567 Automatic update of dependency pyyaml from 5.1.2 to 5.2
  Pipfile.lock
Labels: bot, size/M

#568 Use 8 random digits in the ID instead of 16
  thoth/common/openshift.py
Labels: approved, size/XS

#569 Updated randbits to fix #568
  thoth/common/openshift.py
Labels: approved, size/XS

#571 Release of version 0.9.20
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#572 Sentry's aiohttp integration is supported only for Python 3.7+
  thoth/common/logging.py
Labels: approved, size/S

#574 Release of version 0.9.21
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#575 Change Sphinx theme
  docs/source/conf.py
Labels: approved, size/XS

#576 Automatic update of dependency sentry-sdk from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#577 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#578 Introduce a generic logger adjustment
  README.rst
  thoth/common/logging.py
Labels: approved, size/M

#579 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#580 Add is_s2i flag to adviser scheduling
  thoth/common/openshift.py
Labels: approved, size/XS

#584 Automatic update of dependency openshift from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S

#583 Release of version 0.9.22
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#585 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS

#586 Automatic update of dependency daiquiri from 1.6.0 to 1.6.1
  Pipfile.lock
Labels: bot, size/M

#588 Automatic update of dependency mypy from 0.750 to 0.760
  Pipfile.lock
Labels: bot, size/M

#589 Automatic update of dependency argo-workflows from 2.1.2 to 2.1.3
  Pipfile.lock
Labels: bot, size/XS

#590 Automatic update of dependency argo-workflows from 2.1.3 to 2.1.4
  Pipfile.lock
Labels: bot, size/S

#591 Automatic update of dependency mypy from 0.760 to 0.761
  Pipfile.lock
Labels: bot, size/S
