Repository thoth-station/common, pull requests merged in 2019-06, with the labels that each got.

#399 Supply environment variable for registry and infra namespace for inspections
  thoth/common/openshift.py
Labels: approved, size/XS

#402 Automatic update of dependency sentry-sdk from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot

#404 Release of version 0.8.10
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/L

#403 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#401 Implement Sentry environment
  thoth/common/logging.py
Labels: size/XS

#406 Fix solver temlate handling
  thoth/common/openshift.py
Labels: approved, size/S

#408 Release of version 0.8.11
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#409 Automatic update of dependency pyyaml from 5.1 to 5.1.1
  Pipfile.lock
Labels: bot

#411 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#413 New function for all ConfigMaps
  thoth/common/openshift.py
Labels: approved, size/XS

#412 Fix retrieving pod logs - use OpenShift API
  thoth/common/openshift.py
Labels: approved, size/XS

#415 Release of version 0.9.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#417 Automatic update of dependency sentry-sdk from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#418 Automatic update of dependency sentry-sdk from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#420 Provide method for scheduling graph-refresh on demand
  thoth/common/openshift.py
Labels: approved, size/M

#422 Release of version 0.9.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#423 Automatic update of dependency sentry-sdk from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#424 Automatic update of dependency sentry-sdk from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#425 Automatic update of dependency sentry-sdk from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#426 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot
