Repository thoth-station/common, pull requests merged in 2020-10, with the labels that each got.

#1005 Automatic update of dependency sentry-sdk from 0.17.8 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/L

#1006 Automatic update of dependency pytest from 6.0.2 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/L

#1008 Automatic update of dependency pytest from 6.0.2 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/M

#1010 Qebhwt needs deployment name
  tests/workflows_test.py
  thoth/common/openshift.py
Labels: approved, size/XS

#1012 Release of version 0.20.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#1016 Automatic update of dependency mypy from 0.782 to 0.790
  Pipfile.lock
Labels: approved, bot, size/M

#1013 Added method to initiate kebechet run-url workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#1017 check if workflow has started
  thoth/common/workflows.py
Labels: approved, size/S

#1018 Automatic update of dependency sentry-sdk from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: approved, bot, size/M

#1020 Release of version 0.20.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#1021 Added method to call kebechet admin workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#1023 Release of version 0.20.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#1024 Turn missing env variable warning into an error
  thoth/common/logging.py
Labels: approved, size/XS

#1026 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/M

#1027 Release of version 0.20.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS
