Repository thoth-station/common, pull requests merged in 2020-04, with the labels that each got.

#759 Allow to set use_argo and initialize workflow_manager
  thoth/common/openshift.py
Labels: approved, size/M

#760 Set default loglevel to WARNING
  thoth/common/logging.py
Labels: approved

#762 Release of version 0.12.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#763 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/M

#764 Correct default and typo
  thoth/common/openshift.py
Labels: approved, size/XS

#766 Release of version 0.12.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#767 provide imagestream name while processing template
  thoth/common/openshift.py
Labels: approved, size/L

#769 Release of version 0.12.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#771 Remove parallelism and allowed failures configuration
  thoth/common/openshift.py
Labels: approved, size/XS

#770 Propagate requests and limits for inspection run and build
  thoth/common/openshift.py
Labels: approved, size/XS

#774 Remove assignment of the Dockerfile
  thoth/common/openshift.py
Labels: approved, size/XS

#776 Release of version 0.12.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#777 Provide platform in Thoth's runtime environment config option
  thoth/common/config/runtime_environment.py
Labels: approved, size/XS

#779 Release of version 0.12.10
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#780 Added workflow functions
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#783 Release of version 0.13.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#785 Automatic update of dependency pytest-mypy from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot, size/L

#786 Automatic update of dependency pylint from 2.4.4 to 2.5.0
  Pipfile.lock
Labels: bot, size/S

#787 Renamed to kebechet
  thoth/common/workflows.py
Labels: approved, size/XS

#791 Moved json serialization
  thoth/common/openshift.py
Labels: approved, size/XS

#789 Release of version 0.13.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#793 Automatic update of dependency jsonformatter from 0.1.4 to 0.2.1
  Pipfile.lock
Labels: bot, size/S

#792 New methods to monitor Argo workflows
  thoth/common/workflows.py
Labels: approved, size/L

#796 Release of version 0.13.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#797 Quote unknown configuration entries
  thoth/common/config/runtime_environment.py
Labels: approved, size/XS

#801 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/XS
