Repository thoth-station/common, pull requests merged in 2020-09, with the labels that each got.

#955 Introduce a way to parametrize adviser's predictor
  thoth/common/openshift.py
Labels: approved, size/M

#957 Automatic update of dependency sentry-sdk from 0.16.5 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#958 Release of version 0.17.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#959 Allow users to pick predictor to be used
  thoth/common/openshift.py
Labels: approved, size/XS

#961 Release of version 0.17.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#964 Add Thoth's template for PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#963 Hide default predictor name
  thoth/common/openshift.py
Labels: approved, size/XS

#962 Add more information related to invalid response size
  thoth/common/openshift.py
Labels: approved, size/S

#966 Do not propagate private attribute in to_doct() method
  thoth/common/config/runtime_environment.py
Labels: approved, size/XS

#965 Provenance checks should be scheduled in backend namespace
  thoth/common/workflows.py
Labels: approved, size/XS

#970 Release of version 0.17.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#968 Automatic update of dependency sentry-sdk from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/M

#969 Automatic update of dependency attrs from 20.1.0 to 20.2.0
  Pipfile.lock
Labels: approved, bot, size/M

#971 Provide a method for obtaining a link to justification description
  thoth/common/__init__.py
  thoth/common/helpers.py
  thoth/common/openshift.py
Labels: approved, size/S

#973 Automatic update of dependency sentry-sdk from 0.17.3 to 0.17.4
  Pipfile.lock
Labels: approved, bot, size/S

#974 Release of version 0.18.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#975 Make links to justifications shorter so they fit to terminal output
  thoth/common/helpers.py
Labels: approved, size/XS

#977 Release of version 0.18.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#978 thamos->qebhwt for workflow name
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/S

#980 Release of version 0.18.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#981 No need to provide html suffix
  thoth/common/helpers.py
Labels: approved, size/XS

#982 allow job_id to be passed so we can return it
  thoth/common/openshift.py
Labels: approved, size/S

#984 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/XS

#985 Release of version 0.18.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#987 Fix predictor config propagation when scheduling adviser
  thoth/common/openshift.py
Labels: size/XS

#948 add optional limit for workflows
  thoth/common/workflows.py
Labels: approved, size/S

#989 Automatic update of dependency sentry-sdk from 0.17.4 to 0.17.5
  Pipfile.lock
Labels: approved, bot, size/M

#991 Release of version 0.19.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#992 Improve message logged when obtaining wf node log from cluster fails
  thoth/common/openshift.py
Labels: approved, size/XS

#996 fix pre-commit for common
  thoth/common/openshift.py
Labels: approved, size/XS

#995 Automatic update of dependency sentry-sdk from 0.17.5 to 0.17.6
  Pipfile.lock
Labels: approved, bot, size/M

#994 Rely on S2I specific environment variable, no OpenShift build env vars
  thoth/common/logging.py
Labels: approved, size/XS

#998 Update versions for compatibility between Argo, Kuberneter and Openshift
  Pipfile
  Pipfile.lock
  requirements.txt
  thoth/common/openshift.py
Labels: approved, size/L

#1002 Automatic update of dependency sentry-sdk from 0.17.7 to 0.17.8
  Pipfile.lock
Labels: approved, bot, size/M

#1003 Release of version 0.20.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S
