Repository thoth-station/common, pull requests merged in 2020-11, with the labels that each got.

#1007 get workflow node status
  thoth/common/logging.py
  thoth/common/openshift.py
Labels: approved, size/S

#1029 Automatic update of dependency sentry-sdk from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: approved, bot, size/M

#1030 Automatic update of dependency attrs from 20.2.0 to 20.3.0
  Pipfile.lock
Labels: approved, bot, size/M

#1028 schedule graph sync workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#1033 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/S

#1034 Automatic update of dependency sentry-sdk from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: approved, bot, size/S

#1035 Automatic update of dependency pytest-mypy from 0.7.0 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/S

#1037 Move openshift related code from mi-scheduler
  thoth/common/openshift.py
Labels: approved, size/M

#1038 Automatic update of dependency argo-workflows from 3.5.1 to 3.6.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1043 Pin argo-workflows to a version before 4
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/L
