Repository thoth-station/common, pull requests merged in 2020-03, with the labels that each got.

#702 Adjust inputs for solvers
  thoth/common/openshift.py
Labels: approved, size/XS

#709 Adjust Pipfile and Pipfile.lock
  Pipfile
  Pipfile.lock
Labels: approved

#707 Adjust .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#705 Generalize variables for Ceph storage for workflow
  thoth/common/openshift.py
Labels: approved, size/S

#706 Env adviser ceph
  thoth/common/openshift.py
Labels: approved, size/XS

#704 Release of version 0.10.10
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#711 Release of version 0.10.11
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#712 Automatic update of dependency mypy from 0.761 to 0.770
  Pipfile.lock
Labels: bot, size/M

#714 Introduce Schedule inspection method in Openshift Class
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#713 Fixes for thamos advise
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#715 Modify logic of get_solver_names not to depend on Openshift template
  thoth/common/openshift.py
Labels: approved, size/S

#716 Fix issue with returning None instead of workflow id
  thoth/common/openshift.py
Labels: approved

#718 Adjust solver workflow id
  thoth/common/openshift.py
Labels: approved, size/XS

#720 Automatic update of dependency openshift from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#721 Automatic update of dependency pyyaml from 5.3 to 3.13
  Pipfile.lock
Labels: bot, size/M

#722 Automatic update of dependency pytest-mypy from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot, size/S

#719 Automatic update of dependency pytest from 5.3.5 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#723 Add empty env template
  .env.template
  .gitignore
Labels: approved, size/S

#725 Release of version 0.10.12
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#726 Automatic update of dependency sentry-sdk from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#728 Increase mypy timeout
  setup.py
Labels: approved

#727 Add re_run_adviser_id metadata for qeb-hwt app
  thoth/common/openshift.py
Labels: approved, size/XS

#730 Implement structured logging for cluster deployments
  Pipfile
  Pipfile.lock
  README.rst
  thoth/common/logging.py
Labels: approved, size/L

#732 Release of version 0.11.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot

#733 Release of version 0.12.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XL

#734 added the missing jsonformatter
  requirements.txt
Labels: approved

#738 Release of version 0.12.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#739 Stopping bots
  .github/config.yml
Labels: approved, size/XS

#740 Fix requirements parsing
  setup.py
Labels: approved

#742 Release of version 0.12.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#729 Removed coala bear
  Pipfile
  Pipfile.lock
Labels: human_intervention_required, size/L

#747 Release of version 0.12.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#737 Adjust id for qeb-hwt workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#748 Force JSON logger for all registered loggers
  thoth/common/logging.py
Labels: approved, size/S

#751 Release of version 0.12.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#752 Propagate THOTH_ADVISER_DEV parameter to adviser runs
  thoth/common/openshift.py
Labels: approved

#753 Lock down kubernetes version to 0.10.0 due to CVE-2017-18342
  Pipfile
  requirements.txt
Labels: approved, size/XS

#756 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#758 Release of version 0.12.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS
