Repository thoth-station/common, pull requests merged in 2020-07, with the labels that each got.

#896 Package extract now does not need output to result-api
  thoth/common/openshift.py
Labels: approved, size/XS

#897 Always supply pipeline configuration for dependency monkey
  thoth/common/openshift.py
Labels: approved, size/XS

#899 Release of version 0.14.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#900 Add methods to schedule SI workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#901 Use singular
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#903 Automatic update of dependency sentry-sdk from 0.15.1 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M

#904 Release of version 0.14.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#906 Add parameter to trigger reverse solver run
  thoth/common/openshift.py
Labels: approved, size/XS

#907 Introduce reverse solver workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#908 Parsing solver names can be a class method
  thoth/common/openshift.py
Labels: approved, size/XS

#909 Make methods static
  thoth/common/openshift.py
Labels: approved, size/XS

#911 Automatic update of dependency sentry-sdk from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#912 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/M

#913 Release of version 0.14.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#916 Remove unused env variable
  .env.template
Labels: approved, size/XS

#917 Do not limit latest versions on adviser runs
  thoth/common/openshift.py
Labels: approved, size/XS

#919 Added workflow status wrapper
  thoth/common/openshift.py
Labels: approved, size/S

#921 Automatic update of dependency sentry-sdk from 0.16.1 to 0.16.2
  Pipfile.lock
Labels: approved, bot, size/L

#922 Automatic update of dependency jsonformatter from 0.2.3 to 0.3.0
  Pipfile.lock
Labels: approved, bot, size/L

#923 Release of version 0.15.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS

#926 Rename srcopsmetrics to mi
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/S

#927 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/S

#929 Release of version 0.16.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/XS
