Repository thoth-station/common, pull requests merged in 2020-01, with the labels that each got.

#592 Happy new year!
  docs/source/conf.py
  setup.py
  tests/__init__.py
  tests/base.py
  tests/test_workflows.py
  thoth/common/__init__.py
  thoth/common/config/__init__.py
  thoth/common/config/base.py
  thoth/common/config/hardware_information.py
  thoth/common/config/operating_system.py
  thoth/common/config/runtime_environment.py
  thoth/common/exceptions.py
  thoth/common/helpers.py
  thoth/common/json.py
  thoth/common/logging.py
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: size/M

#594 Raise not found error if configmap was not found
  thoth/common/openshift.py
Labels: approved, size/XS

#595 Busy wait on configmap creation to make sure cm gets propagated in the cluster
  thoth/common/openshift.py
Labels: approved, size/S

#597 Automatic update of dependency pyyaml from 5.2 to 5.3
  Pipfile.lock
Labels: bot, size/L

#598 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/XS

#596 Be more aggressive with busy wait
  thoth/common/openshift.py
Labels: approved, size/XS

#593 WIP: Schedule adviser workflow
  thoth/common/workflows.py
Labels: approved, do-not-merge/work-in-progress, size/S

#601 Release of version 0.9.23
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#602 Automatic update of dependency sentry-sdk from 0.13.5 to 0.14.0
  Pipfile.lock
Labels: bot, size/S

#603 Migration to Argo workflow for Adviser
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#605 Fix relative import issue
  thoth/common/openshift.py
Labels: approved, size/XS

#606 I had to do it... it was so annoying
  thoth/common/logging.py
Labels: approved, size/XS

#607 Pass OpenShift instance instead of dynamic client to workflow manager
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/S

#608 Add missing argument to dependency monkey runs
  thoth/common/openshift.py
Labels: approved, size/XS

#609 Fix decision type environment variable name
  thoth/common/openshift.py
Labels: approved, size/XS

#611 Release of version 0.9.24
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#612 Enable providing pipeline configuration to Dependency Monkey
  thoth/common/openshift.py
Labels: approved, size/XS

#614 Release of version 0.9.25
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#615 Remove wrong default value to run Dependency Monkey and Adviser
  thoth/common/openshift.py
Labels: approved, size/XS

#617 Release of version 0.9.26
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#618 Solver runs with Argo workflows
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/M

#619 Automatic update of dependency daiquiri from 1.6.1 to 2.0.0
  Pipfile.lock
Labels: bot, size/L

#620 Try to avoid timing issues between job and configmap creation
  thoth/common/openshift.py
Labels: approved, size/S

#622 Release of version 0.9.27
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#623 Use thoth.common as a root logger for logging information
  thoth/common/logging.py
Labels: approved, size/XS

#625 Release of version 0.9.28
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#626 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#627 Correct solver id input
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/XS

#628 Rename template used by workload opeartor
  thoth/common/openshift.py
Labels: approved, size/S

#630 Release of version 0.9.29
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#631 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#634 Automatic update of dependency sentry-sdk from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/S

#635 Fixed the spelling mistake causing issue
  thoth/common/openshift.py
Labels: approved, size/XS

#636 Thamos workflow for GitHub App Qeb-Hwt
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#642 Modify method to accept None
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/S

#641 Adjust exception for thamos advise workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#640 Release of version 0.9.30
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#637 added xml coverage report
  .gitignore
  setup.py
Labels: approved, size/XS

#638 added pre-commit and did a little bit of coala cleanup
  .coafile
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#646 Release of version 0.9.31
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#645 Do not cache fully specified environment check
  thoth/common/config/runtime_environment.py
Labels: approved, size/S

#633 Sentryfilter
  README.rst
  thoth/common/logging.py
Labels: approved, size/M

#647 Added log error
  thoth/common/logging.py
Labels: approved, size/XS

#649 Automatic update of dependency pre-commit from 1.21.0 to 2.0.0
  Pipfile.lock
Labels: bot, size/M

#648 Extend parameters for Adviser
  thoth/common/openshift.py
Labels: approved, size/M

#651 Release of version 0.10.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#652 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/S

#653 Automatic update of dependency pre-commit from 2.0.0 to 2.0.1
  Pipfile.lock
Labels: bot, size/XS

#654 function to sync build analyzers report
  thoth/common/openshift.py
Labels: approved, size/S

#655 Add host parameter for Thamos GitHub App
  thoth/common/openshift.py
Labels: approved, size/XS

#657 Release of version 0.10.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS
