Repository thoth-station/common, pull requests merged in 2020-02, with the labels that each got.

#658 Remove prefix to avoid error in Thoth components
  thoth/common/workflows.py
Labels: approved, size/XS

#660 Release of version 0.10.2
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#663 Add method to retrieve image streams
  thoth/common/openshift.py
Labels: approved, size/XS

#664 Adjust parameters for Thamos Workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#662 Make decision type and recommendation type lowercase
  thoth/common/openshift.py
Labels: approved, size/XS

#666 Release of version 0.10.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#669 add missing parameter to advise method
  thoth/common/openshift.py
Labels: approved, size/XS

#668 Change template name for Argo migration
  thoth/common/openshift.py
Labels: approved, size/S

#672 Release of version 0.10.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#674 Remove revision from metadata
  thoth/common/openshift.py
Labels: approved, size/XS

#676 Release of version 0.10.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#677 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#679 Fix confusion with lowercase decision type
  thoth/common/openshift.py
Labels: approved, size/XS

#681 Simplify dictionary handling with inlined dict
  thoth/common/openshift.py
Labels: approved, size/S

#683 Simplify dictionary handling with dict instantiation
  thoth/common/openshift.py
Labels: approved, size/S

#685 Fix check for default value in workflow template
  thoth/common/workflows.py
Labels: approved, size/XS

#682 Propagate missing is_s2i flag to adviser metadata
  thoth/common/openshift.py
Labels: approved, size/XS

#684 Simplfiy condition, do not use nested if
  thoth/common/openshift.py
Labels: approved, size/S

#680 Add locked application stack optionally to adviser workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#678 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: size/M

#687 Release of version 0.10.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#688 Always use Argo for thamos workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#690 Release of version 0.10.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#691 Missing metadata parameters
  thoth/common/openshift.py
Labels: approved, size/XS

#661 Openshift methods for inspection workflows
  thoth/common/openshift.py
Labels: approved, size/L

#694 Handle debug parameter for adviser in argo workflows
  thoth/common/openshift.py
Labels: approved, size/XS

#695 Added get_workflow_status method
  thoth/common/openshift.py
Labels: approved, size/S

#696 Correct datatype
  thoth/common/openshift.py
Labels: approved, size/S

#698 Release of version 0.10.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#699 Migrate method to be used for graph-refresh-job switching to Argo for solvers
  thoth/common/openshift.py
Labels: approved, size/S

#701 Release of version 0.10.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS
