Repository thoth-station/common, pull requests merged in 2020-05, with the labels that each got.

#803 Release of version 0.13.3
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#805 Automatic update of dependency pylint from 2.5.0 to 2.5.2
  Pipfile.lock
Labels: bot, size/S

#806 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/S

#809 Automatic update of dependency sentry-sdk from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot, size/S

#811 Add source type for Thoth adviser integrations
  thoth/common/__init__.py
  thoth/common/enums.py
  thoth/common/openshift.py
Labels: approved, size/M

#815 Add exception for integrations
  thoth/common/exceptions.py
Labels: approved, size/XS

#813 Adjust enums
  thoth/common/enums.py
  thoth/common/openshift.py
Labels: approved, size/S

#814 Use solvers ConfigMap
  thoth/common/openshift.py
Labels: approved, size/XS

#817 New check method for Qeb-HWt inputs
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: approved, size/M

#818 Add missing parameters
  thoth/common/openshift.py
Labels: approved, size/S

#820 Release of version 0.13.4
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#822 Introduce logic for solver
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: approved, size/M

#824 Release of version 0.13.5
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#825 Missing self
  thoth/common/openshift.py
Labels: approved, size/S

#827 Release of version 0.13.6
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#828 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/M

#829 Missing self in methods
  thoth/common/openshift.py
Labels: approved, size/XS

#831 make output in solver optional
  thoth/common/openshift.py
Labels: approved, size/XS

#832 Release of version 0.13.7
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS

#834 only change pre-commit config
  .pre-commit-config.yaml
Labels: approved, size/M

#835 Be consistent
  .pre-commit-config.yaml
  thoth/common/openshift.py
Labels: approved, size/M

#838 Release of version 0.13.8
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XS
