Repository thoth-station/common, pull requests merged in 2020-06, with the labels that each got.

#833 Use precommit
  .coafile
  .env.template
  .github/config.yml
  .gitignore
  .zuul.yaml
  MANIFEST.in
  README.rst
  docs/source/conf.py
  setup.py
  tests/base_test.py
  tests/workflows_test.py
  thoth/common/__init__.py
  thoth/common/config/__init__.py
  thoth/common/config/base.py
  thoth/common/config/runtime_environment.py
  thoth/common/helpers.py
  thoth/common/logging.py
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/XL

#841 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#842 Automatic update of dependency mypy from 0.770 to 0.780
  Pipfile.lock
Labels: bot, size/M

#845 :sparkles: standard pre-commit-config
  .pre-commit-config.yaml
  thoth/common/openshift.py
Labels: approved, size/XS

#837 Introudce method for verifying Kebechet inputs
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: approved, size/M, thoth/human_intervention_required

#847 Automatic update of dependency pylint from 2.5.2 to 2.5.3
  Pipfile.lock
Labels: bot, size/M

#849 Release of version 0.13.9
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/XL

#861 move Lazy to common helpers from python helpers
  thoth/common/__init__.py
  thoth/common/helpers.py
Labels: approved, size/S

#846 add submit and schedule methods for SI's
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#862 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: bot, size/M

#843 Setup Sentry traces sample rate
  thoth/common/logging.py
Labels: approved, size/S

#866 Release of version 0.13.12
  CHANGELOG.md
  thoth/common/__init__.py
Labels: bot, size/S

#863 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: bot, size/XS

#860 Correct serialization of Enum
  thoth/common/openshift.py
Labels: approved, size/S

#870 Accept alternative datetime format string used by PyPI
  thoth/common/helpers.py
Labels: approved, size/XS

#868 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/M

#869 Automatic update of dependency sentry-sdk from 0.14.4 to 0.15.1
  Pipfile.lock
Labels: bot, size/XS

#871 Automatic update of dependency mypy from 0.780 to 0.781
  Pipfile.lock
Labels: approved, bot, size/M

#874 Remove build dependencies component
  thoth/common/openshift.py
Labels: approved, size/M

#877 Schedule Dependency Monkey using Argo workflows
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#878 Remove variable not required
  thoth/common/helpers.py
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/XS

#880 Automatic update of dependency mypy from 0.781 to 0.782
  Pipfile.lock
Labels: approved, bot, size/M

#879 some reformatting
  .gitignore
Labels: approved, size/XS

#881 some reformatting
  thoth/common/openshift.py
Labels: approved, size/S

#883 Source type enum fix
  thoth/common/openshift.py
Labels: approved, size/M

#885 Release of version 0.13.13
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#888 Remove graph sync jobs
  thoth/common/openshift.py
Labels: approved, size/L

#876 Build analysis workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#891 Use Argo workflows for package-extract
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#887 Introduce provenance-checker Argo workflow
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#890 Remove package analyzer job
  thoth/common/openshift.py
Labels: approved, size/M

#893 Remove kebechet jobs they are now part of workflows
  thoth/common/openshift.py
Labels: approved, size/L

#894 Drop legacy workload operator, use only Argo workflows
  thoth/common/openshift.py
Labels: approved, size/L

#895 Drop remaining workload-operator bits
  thoth/common/openshift.py
Labels: approved, size/L
