Repository thoth-station/common, pull requests merged in 2020-08, with the labels that each got.

#933 Automatic update of dependency sentry-sdk from 0.16.2 to 0.16.3
  Pipfile.lock
Labels: approved, bot, size/S

#934 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/S

#932 set source_type_enum None when soure_type not set
  thoth/common/openshift.py
Labels: approved, size/XS

#935 Add long_description_content_type
  setup.py
Labels: approved, size/XS

#936 Introduce raw specification parameter to be used when storing on Ceph
  thoth/common/openshift.py
Labels: approved, size/XS

#938 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/S

#937 Automatic update of dependency sentry-sdk from 0.16.3 to 0.16.5
  Pipfile.lock
Labels: approved, bot, size/XS

#940 Release of version 0.16.1
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#941 Remove IMAGE_STREAM_NAMESPACE env
  thoth/common/openshift.py
Labels: approved, size/XS

#943 Automatic update of dependency attrs from 19.3.0 to 20.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#945 Automatic update of dependency pylint from 2.5.3 to 2.6.0
  Pipfile.lock
Labels: approved, bot, size/S

#946 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/S

#949 Add a routine for obtaining logs from workflow nodes
  thoth/common/openshift.py
Labels: size/S

#953 Fix typing
  thoth/common/openshift.py
Labels: approved, size/XS

#952 Release of version 0.17.0
  CHANGELOG.md
  thoth/common/__init__.py
Labels: approved, bot, size/S

#918 Provide cached Python package version tuple
  thoth/common/config/runtime_environment.py
Labels: approved, size/S
