Repository thoth-station/common, pull requests merged in 2021-01, with the labels that each got.

#1061 Bump black version
  .pre-commit-config.yaml
Labels: approved, size/XS

#1060 Move normalization functions to helpers
  thoth/common/__init__.py
  thoth/common/helpers.py
  thoth/common/openshift.py
Labels: approved, size/M

#1066 Remove AttrDict from requirements
  Pipfile
  Pipfile.lock
  thoth/common/workflows.py
Labels: approved, size/M

#1069 Increase random bits used to distinguish workflows
  thoth/common/openshift.py
Labels: approved, size/XS

#1073 Propagate build log document id to build analysis workflow
  thoth/common/openshift.py
Labels: approved, size/XS

#1076 Extend parameters supplied to build analysis
  thoth/common/openshift.py
Labels: approved, size/M

#1052 Add method to schedule graph-update-schema job
  thoth/common/openshift.py
Labels: approved, size/M

#1083 Provide image metadata for package-extract
  thoth/common/openshift.py
Labels: approved, size/XS

#1085 Provide additional build-analysis metadata so documents are traceable
  thoth/common/openshift.py
Labels: approved, sig/build, size/XS

#1088 Add is_external flag to build analysis
  thoth/common/openshift.py
Labels: approved, size/XS

#1091 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#1093 Revisit generating id to avoid hash collisions
  thoth/common/openshift.py
Labels: approved, size/S

#1072 Extend Thamos configuration file
  thoth/common/config/hardware_information.py
  thoth/common/config/runtime_environment.py
Labels: approved, size/XS

#1098 add enum for internal triggers
  .pre-commit-config.yaml
  thoth/common/enums.py
Labels: approved, size/S
