Repository thoth-station/common, pull requests merged in 2021-07, with the labels that each got.

#1176 Remove qeb-hwt and github-app bits
  thoth/common/enums.py
  thoth/common/exceptions.py
  thoth/common/openshift.py
  thoth/common/workflows.py
Labels: approved, size/L

#1171 update advises
  thoth/common/openshift.py
Labels: approved, size/XS

#1183 get update info from kebechet meta
  thoth/common/openshift.py
Labels: approved, size/S

#1188 Introduce method to expose cache expiration
  thoth/common/exceptions.py
  thoth/common/openshift.py
Labels: approved, lgtm, size/M
