Repository thoth-station/common, pull requests merged in 2021-06, with the labels that each got.

#1162 Provide force_sync to solver schedule methods
  mypy.ini
  thoth/common/openshift.py
Labels: approved, size/XS

#1172 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, lgtm, size/S

#1173 updating the pytest fixes
  .prow.yaml
  mypy.ini
  setup.py
Labels: approved, size/XS

#1175 set badges for easy access to content
  README.rst
Labels: approved, size/S
