Repository thoth-station/common, pull requests merged in 2022-04, with the labels that each got.

#1253 fix pre-commit by removing mypy
  .pre-commit-config.yaml
  .prow.yaml
  Pipfile
  Pipfile.lock
  mypy.ini
  thoth/common/openshift.py
Labels: size/L

#1249 Replace slash with dash in repo slug [scheduling mi workflows]
  thoth/common/openshift.py
Labels: size/S

#1254 bump kubernetes version for common image
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/M, lgtm
