Repository thoth-station/common, pull requests merged in 2022-03, with the labels that each got.

#1235 Drop rfc5424logging and syslog
  mypy.ini
  thoth/common/logging.py
Labels: approved, size/S

#1234 Add `create_knowledge` parameter, change workflow name
  thoth/common/openshift.py
Labels: approved, size/S, lgtm

#1242 Remove `rfc5424-logging-handler` from dependencies
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#1231 Send messages based on template defaults, do not hardcode
  thoth/common/openshift.py
Labels: size/S
