Repository thoth-station/common, pull requests merged in 2022-08, with the labels that each got.

#1275 Add mypy back to pre-commit
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  mypy.ini
  thoth/common/config/base.py
  thoth/common/config/runtime_environment.py
  thoth/common/logging.py
  thoth/common/workflows.py
Labels: approved, size/L, lgtm

#1279 Pinned Kubernetes version to 11.0.0
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#1283 Fix pytest
  requirements.txt
Labels: size/XS
